/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace IEtherZDAOChef {
  export type ZDAOConfigStruct = {
    name: string;
    gnosisSafe: string;
    token: string;
    amount: BigNumberish;
    minPeriod: BigNumberish;
    isRelativeMajority: boolean;
    threshold: BigNumberish;
  };

  export type ZDAOConfigStructOutput = [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    boolean,
    BigNumber
  ] & {
    name: string;
    gnosisSafe: string;
    token: string;
    amount: BigNumber;
    minPeriod: BigNumber;
    isRelativeMajority: boolean;
    threshold: BigNumber;
  };

  export type ZDAORecordStruct = {
    id: BigNumberish;
    zDAO: string;
    associatedzNAs: BigNumberish[];
  };

  export type ZDAORecordStructOutput = [BigNumber, string, BigNumber[]] & {
    id: BigNumber;
    zDAO: string;
    associatedzNAs: BigNumber[];
  };
}

export interface IEtherZDAOChefInterface extends utils.Interface {
  contractName: "IEtherZDAOChef";
  functions: {
    "addNewDAO(uint256,(string,address,address,uint256,uint256,bool,uint256))": FunctionFragment;
    "addZNAAssociation(uint256,uint256)": FunctionFragment;
    "doeszDAOExistForzNA(uint256)": FunctionFragment;
    "getzDAOById(uint256)": FunctionFragment;
    "getzDaoByZNA(uint256)": FunctionFragment;
    "listzDAOs(uint256,uint256)": FunctionFragment;
    "numberOfzDAOs()": FunctionFragment;
    "removeDAO(uint256)": FunctionFragment;
    "removeZNAAssociation(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addNewDAO",
    values: [BigNumberish, IEtherZDAOChef.ZDAOConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addZNAAssociation",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "doeszDAOExistForzNA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getzDAOById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getzDaoByZNA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listzDAOs",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfzDAOs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeDAO",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeZNAAssociation",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addNewDAO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addZNAAssociation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doeszDAOExistForzNA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getzDAOById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getzDaoByZNA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listzDAOs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numberOfzDAOs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removeDAO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeZNAAssociation",
    data: BytesLike
  ): Result;

  events: {
    "DAOCreated(uint256,address,address)": EventFragment;
    "DAODestroyed(uint256)": EventFragment;
    "LinkAdded(uint256,uint256)": EventFragment;
    "LinkRemoved(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DAOCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DAODestroyed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LinkAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LinkRemoved"): EventFragment;
}

export type DAOCreatedEvent = TypedEvent<
  [BigNumber, string, string],
  { _daoId: BigNumber; _creator: string; _zDAO: string }
>;

export type DAOCreatedEventFilter = TypedEventFilter<DAOCreatedEvent>;

export type DAODestroyedEvent = TypedEvent<[BigNumber], { _daoId: BigNumber }>;

export type DAODestroyedEventFilter = TypedEventFilter<DAODestroyedEvent>;

export type LinkAddedEvent = TypedEvent<
  [BigNumber, BigNumber],
  { _daoId: BigNumber; _zNA: BigNumber }
>;

export type LinkAddedEventFilter = TypedEventFilter<LinkAddedEvent>;

export type LinkRemovedEvent = TypedEvent<
  [BigNumber, BigNumber],
  { _daoId: BigNumber; _zNA: BigNumber }
>;

export type LinkRemovedEventFilter = TypedEventFilter<LinkRemovedEvent>;

export interface IEtherZDAOChef extends BaseContract {
  contractName: "IEtherZDAOChef";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IEtherZDAOChefInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addNewDAO(
      _zNA: BigNumberish,
      _zDAOConfig: IEtherZDAOChef.ZDAOConfigStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    doeszDAOExistForzNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getzDAOById(
      _daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IEtherZDAOChef.ZDAORecordStructOutput]>;

    getzDaoByZNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IEtherZDAOChef.ZDAORecordStructOutput]>;

    listzDAOs(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IEtherZDAOChef.ZDAORecordStructOutput[]]>;

    numberOfzDAOs(overrides?: CallOverrides): Promise<[BigNumber]>;

    removeDAO(
      _daoId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addNewDAO(
    _zNA: BigNumberish,
    _zDAOConfig: IEtherZDAOChef.ZDAOConfigStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addZNAAssociation(
    _daoId: BigNumberish,
    _zNA: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  doeszDAOExistForzNA(
    _zNA: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getzDAOById(
    _daoId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IEtherZDAOChef.ZDAORecordStructOutput>;

  getzDaoByZNA(
    _zNA: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IEtherZDAOChef.ZDAORecordStructOutput>;

  listzDAOs(
    _startIndex: BigNumberish,
    _endIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IEtherZDAOChef.ZDAORecordStructOutput[]>;

  numberOfzDAOs(overrides?: CallOverrides): Promise<BigNumber>;

  removeDAO(
    _daoId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeZNAAssociation(
    _daoId: BigNumberish,
    _zNA: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addNewDAO(
      _zNA: BigNumberish,
      _zDAOConfig: IEtherZDAOChef.ZDAOConfigStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    addZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    doeszDAOExistForzNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getzDAOById(
      _daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IEtherZDAOChef.ZDAORecordStructOutput>;

    getzDaoByZNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IEtherZDAOChef.ZDAORecordStructOutput>;

    listzDAOs(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IEtherZDAOChef.ZDAORecordStructOutput[]>;

    numberOfzDAOs(overrides?: CallOverrides): Promise<BigNumber>;

    removeDAO(_daoId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    removeZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DAOCreated(uint256,address,address)"(
      _daoId?: BigNumberish | null,
      _creator?: string | null,
      _zDAO?: string | null
    ): DAOCreatedEventFilter;
    DAOCreated(
      _daoId?: BigNumberish | null,
      _creator?: string | null,
      _zDAO?: string | null
    ): DAOCreatedEventFilter;

    "DAODestroyed(uint256)"(
      _daoId?: BigNumberish | null
    ): DAODestroyedEventFilter;
    DAODestroyed(_daoId?: BigNumberish | null): DAODestroyedEventFilter;

    "LinkAdded(uint256,uint256)"(
      _daoId?: BigNumberish | null,
      _zNA?: BigNumberish | null
    ): LinkAddedEventFilter;
    LinkAdded(
      _daoId?: BigNumberish | null,
      _zNA?: BigNumberish | null
    ): LinkAddedEventFilter;

    "LinkRemoved(uint256,uint256)"(
      _daoId?: BigNumberish | null,
      _zNA?: BigNumberish | null
    ): LinkRemovedEventFilter;
    LinkRemoved(
      _daoId?: BigNumberish | null,
      _zNA?: BigNumberish | null
    ): LinkRemovedEventFilter;
  };

  estimateGas: {
    addNewDAO(
      _zNA: BigNumberish,
      _zDAOConfig: IEtherZDAOChef.ZDAOConfigStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    doeszDAOExistForzNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getzDAOById(
      _daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getzDaoByZNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listzDAOs(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberOfzDAOs(overrides?: CallOverrides): Promise<BigNumber>;

    removeDAO(
      _daoId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addNewDAO(
      _zNA: BigNumberish,
      _zDAOConfig: IEtherZDAOChef.ZDAOConfigStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    doeszDAOExistForzNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getzDAOById(
      _daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getzDaoByZNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listzDAOs(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberOfzDAOs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeDAO(
      _daoId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
