/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace IEtherZDAOChef {
  export type ZDAOConfigStruct = {
    title: string;
    gnosisSafe: string;
    token: string;
    amount: BigNumberish;
    duration: BigNumberish;
    votingThreshold: BigNumberish;
    minimumVotingParticipants: BigNumberish;
    minimumTotalVotingTokens: BigNumberish;
    isRelativeMajority: boolean;
  };

  export type ZDAOConfigStructOutput = [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean
  ] & {
    title: string;
    gnosisSafe: string;
    token: string;
    amount: BigNumber;
    duration: BigNumber;
    votingThreshold: BigNumber;
    minimumVotingParticipants: BigNumber;
    minimumTotalVotingTokens: BigNumber;
    isRelativeMajority: boolean;
  };

  export type ZDAORecordStruct = {
    id: BigNumberish;
    zDAO: string;
    associatedzNAs: BigNumberish[];
  };

  export type ZDAORecordStructOutput = [BigNumber, string, BigNumber[]] & {
    id: BigNumber;
    zDAO: string;
    associatedzNAs: BigNumber[];
  };
}

export interface IEtherZDAOChefInterface extends utils.Interface {
  contractName: "IEtherZDAOChef";
  functions: {
    "addNewDAO(uint256,(string,address,address,uint256,uint256,uint256,uint256,uint256,bool))": FunctionFragment;
    "addZNAAssociation(uint256,uint256)": FunctionFragment;
    "cancelProposal(uint256,uint256)": FunctionFragment;
    "createProposal(uint256,address,uint256,bytes,string)": FunctionFragment;
    "doeszDAOExistForzNA(uint256)": FunctionFragment;
    "executeProposal(uint256,uint256)": FunctionFragment;
    "getzDAOById(uint256)": FunctionFragment;
    "getzDaoByZNA(uint256)": FunctionFragment;
    "listzDAOs(uint256,uint256)": FunctionFragment;
    "numberOfzDAOs()": FunctionFragment;
    "removeDAO(uint256)": FunctionFragment;
    "removeZNAAssociation(uint256,uint256)": FunctionFragment;
    "setDAOGnosisSafe(uint256,address)": FunctionFragment;
    "setDAOVotingToken(uint256,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addNewDAO",
    values: [BigNumberish, IEtherZDAOChef.ZDAOConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addZNAAssociation",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelProposal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [BigNumberish, string, BigNumberish, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "doeszDAOExistForzNA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getzDAOById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getzDaoByZNA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listzDAOs",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfzDAOs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeDAO",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeZNAAssociation",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDAOGnosisSafe",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDAOVotingToken",
    values: [BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addNewDAO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addZNAAssociation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doeszDAOExistForzNA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getzDAOById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getzDaoByZNA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listzDAOs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numberOfzDAOs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removeDAO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeZNAAssociation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDAOGnosisSafe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDAOVotingToken",
    data: BytesLike
  ): Result;

  events: {
    "DAOCreated(uint256,address,address)": EventFragment;
    "DAODestroyed(uint256)": EventFragment;
    "DAOUpdateGnosisSafe(uint256,address)": EventFragment;
    "DAOUpdateVotingtoken(uint256,address,uint256)": EventFragment;
    "LinkAdded(uint256,uint256)": EventFragment;
    "LinkRemoved(uint256,uint256)": EventFragment;
    "ProposalCanceled(uint256,uint256,address)": EventFragment;
    "ProposalCollected(uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "ProposalCreated(uint256,uint256,address,uint256)": EventFragment;
    "ProposalExecuted(uint256,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DAOCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DAODestroyed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DAOUpdateGnosisSafe"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DAOUpdateVotingtoken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LinkAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LinkRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalCanceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalCollected"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalExecuted"): EventFragment;
}

export type DAOCreatedEvent = TypedEvent<
  [BigNumber, string, string],
  { _daoId: BigNumber; _creator: string; _zDAO: string }
>;

export type DAOCreatedEventFilter = TypedEventFilter<DAOCreatedEvent>;

export type DAODestroyedEvent = TypedEvent<[BigNumber], { _daoId: BigNumber }>;

export type DAODestroyedEventFilter = TypedEventFilter<DAODestroyedEvent>;

export type DAOUpdateGnosisSafeEvent = TypedEvent<
  [BigNumber, string],
  { _daoId: BigNumber; _gnosisSafe: string }
>;

export type DAOUpdateGnosisSafeEventFilter =
  TypedEventFilter<DAOUpdateGnosisSafeEvent>;

export type DAOUpdateVotingtokenEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  { _daoId: BigNumber; _token: string; _amount: BigNumber }
>;

export type DAOUpdateVotingtokenEventFilter =
  TypedEventFilter<DAOUpdateVotingtokenEvent>;

export type LinkAddedEvent = TypedEvent<
  [BigNumber, BigNumber],
  { _daoId: BigNumber; _zNA: BigNumber }
>;

export type LinkAddedEventFilter = TypedEventFilter<LinkAddedEvent>;

export type LinkRemovedEvent = TypedEvent<
  [BigNumber, BigNumber],
  { _daoId: BigNumber; _zNA: BigNumber }
>;

export type LinkRemovedEventFilter = TypedEventFilter<LinkRemovedEvent>;

export type ProposalCanceledEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  { _zDAOId: BigNumber; _proposalId: BigNumber; _cancelBy: string }
>;

export type ProposalCanceledEventFilter =
  TypedEventFilter<ProposalCanceledEvent>;

export type ProposalCollectedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    _zDAOId: BigNumber;
    _propoalId: BigNumber;
    _voters: BigNumber;
    _yes: BigNumber;
    _no: BigNumber;
  }
>;

export type ProposalCollectedEventFilter =
  TypedEventFilter<ProposalCollectedEvent>;

export type ProposalCreatedEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber],
  {
    _zDAOId: BigNumber;
    _proposalId: BigNumber;
    _createdBy: string;
    _snapshot: BigNumber;
  }
>;

export type ProposalCreatedEventFilter = TypedEventFilter<ProposalCreatedEvent>;

export type ProposalExecutedEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  { _zDAOId: BigNumber; _proposalId: BigNumber; _executeBy: string }
>;

export type ProposalExecutedEventFilter =
  TypedEventFilter<ProposalExecutedEvent>;

export interface IEtherZDAOChef extends BaseContract {
  contractName: "IEtherZDAOChef";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IEtherZDAOChefInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addNewDAO(
      _zNA: BigNumberish,
      _zDAOConfig: IEtherZDAOChef.ZDAOConfigStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelProposal(
      _daoId: BigNumberish,
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createProposal(
      _daoId: BigNumberish,
      _target: string,
      _value: BigNumberish,
      _data: BytesLike,
      _ipfs: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    doeszDAOExistForzNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    executeProposal(
      _daoId: BigNumberish,
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getzDAOById(
      _daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [IEtherZDAOChef.ZDAORecordStructOutput] & {
        records: IEtherZDAOChef.ZDAORecordStructOutput;
      }
    >;

    getzDaoByZNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IEtherZDAOChef.ZDAORecordStructOutput]>;

    listzDAOs(
      _startIndex: BigNumberish,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [IEtherZDAOChef.ZDAORecordStructOutput[]] & {
        records: IEtherZDAOChef.ZDAORecordStructOutput[];
      }
    >;

    numberOfzDAOs(overrides?: CallOverrides): Promise<[BigNumber]>;

    removeDAO(
      _daoId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDAOGnosisSafe(
      _daoId: BigNumberish,
      _gnosisSafe: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDAOVotingToken(
      _daoId: BigNumberish,
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addNewDAO(
    _zNA: BigNumberish,
    _zDAOConfig: IEtherZDAOChef.ZDAOConfigStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addZNAAssociation(
    _daoId: BigNumberish,
    _zNA: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelProposal(
    _daoId: BigNumberish,
    _proposalId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createProposal(
    _daoId: BigNumberish,
    _target: string,
    _value: BigNumberish,
    _data: BytesLike,
    _ipfs: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  doeszDAOExistForzNA(
    _zNA: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  executeProposal(
    _daoId: BigNumberish,
    _proposalId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getzDAOById(
    _daoId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IEtherZDAOChef.ZDAORecordStructOutput>;

  getzDaoByZNA(
    _zNA: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IEtherZDAOChef.ZDAORecordStructOutput>;

  listzDAOs(
    _startIndex: BigNumberish,
    _count: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IEtherZDAOChef.ZDAORecordStructOutput[]>;

  numberOfzDAOs(overrides?: CallOverrides): Promise<BigNumber>;

  removeDAO(
    _daoId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeZNAAssociation(
    _daoId: BigNumberish,
    _zNA: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDAOGnosisSafe(
    _daoId: BigNumberish,
    _gnosisSafe: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDAOVotingToken(
    _daoId: BigNumberish,
    _token: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addNewDAO(
      _zNA: BigNumberish,
      _zDAOConfig: IEtherZDAOChef.ZDAOConfigStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    addZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelProposal(
      _daoId: BigNumberish,
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createProposal(
      _daoId: BigNumberish,
      _target: string,
      _value: BigNumberish,
      _data: BytesLike,
      _ipfs: string,
      overrides?: CallOverrides
    ): Promise<void>;

    doeszDAOExistForzNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    executeProposal(
      _daoId: BigNumberish,
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getzDAOById(
      _daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IEtherZDAOChef.ZDAORecordStructOutput>;

    getzDaoByZNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IEtherZDAOChef.ZDAORecordStructOutput>;

    listzDAOs(
      _startIndex: BigNumberish,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IEtherZDAOChef.ZDAORecordStructOutput[]>;

    numberOfzDAOs(overrides?: CallOverrides): Promise<BigNumber>;

    removeDAO(_daoId: BigNumberish, overrides?: CallOverrides): Promise<void>;

    removeZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setDAOGnosisSafe(
      _daoId: BigNumberish,
      _gnosisSafe: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setDAOVotingToken(
      _daoId: BigNumberish,
      _token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DAOCreated(uint256,address,address)"(
      _daoId?: BigNumberish | null,
      _creator?: string | null,
      _zDAO?: string | null
    ): DAOCreatedEventFilter;
    DAOCreated(
      _daoId?: BigNumberish | null,
      _creator?: string | null,
      _zDAO?: string | null
    ): DAOCreatedEventFilter;

    "DAODestroyed(uint256)"(
      _daoId?: BigNumberish | null
    ): DAODestroyedEventFilter;
    DAODestroyed(_daoId?: BigNumberish | null): DAODestroyedEventFilter;

    "DAOUpdateGnosisSafe(uint256,address)"(
      _daoId?: BigNumberish | null,
      _gnosisSafe?: string | null
    ): DAOUpdateGnosisSafeEventFilter;
    DAOUpdateGnosisSafe(
      _daoId?: BigNumberish | null,
      _gnosisSafe?: string | null
    ): DAOUpdateGnosisSafeEventFilter;

    "DAOUpdateVotingtoken(uint256,address,uint256)"(
      _daoId?: BigNumberish | null,
      _token?: string | null,
      _amount?: BigNumberish | null
    ): DAOUpdateVotingtokenEventFilter;
    DAOUpdateVotingtoken(
      _daoId?: BigNumberish | null,
      _token?: string | null,
      _amount?: BigNumberish | null
    ): DAOUpdateVotingtokenEventFilter;

    "LinkAdded(uint256,uint256)"(
      _daoId?: BigNumberish | null,
      _zNA?: BigNumberish | null
    ): LinkAddedEventFilter;
    LinkAdded(
      _daoId?: BigNumberish | null,
      _zNA?: BigNumberish | null
    ): LinkAddedEventFilter;

    "LinkRemoved(uint256,uint256)"(
      _daoId?: BigNumberish | null,
      _zNA?: BigNumberish | null
    ): LinkRemovedEventFilter;
    LinkRemoved(
      _daoId?: BigNumberish | null,
      _zNA?: BigNumberish | null
    ): LinkRemovedEventFilter;

    "ProposalCanceled(uint256,uint256,address)"(
      _zDAOId?: BigNumberish | null,
      _proposalId?: BigNumberish | null,
      _cancelBy?: string | null
    ): ProposalCanceledEventFilter;
    ProposalCanceled(
      _zDAOId?: BigNumberish | null,
      _proposalId?: BigNumberish | null,
      _cancelBy?: string | null
    ): ProposalCanceledEventFilter;

    "ProposalCollected(uint256,uint256,uint256,uint256,uint256)"(
      _zDAOId?: BigNumberish | null,
      _propoalId?: BigNumberish | null,
      _voters?: null,
      _yes?: null,
      _no?: null
    ): ProposalCollectedEventFilter;
    ProposalCollected(
      _zDAOId?: BigNumberish | null,
      _propoalId?: BigNumberish | null,
      _voters?: null,
      _yes?: null,
      _no?: null
    ): ProposalCollectedEventFilter;

    "ProposalCreated(uint256,uint256,address,uint256)"(
      _zDAOId?: BigNumberish | null,
      _proposalId?: BigNumberish | null,
      _createdBy?: string | null,
      _snapshot?: null
    ): ProposalCreatedEventFilter;
    ProposalCreated(
      _zDAOId?: BigNumberish | null,
      _proposalId?: BigNumberish | null,
      _createdBy?: string | null,
      _snapshot?: null
    ): ProposalCreatedEventFilter;

    "ProposalExecuted(uint256,uint256,address)"(
      _zDAOId?: BigNumberish | null,
      _proposalId?: BigNumberish | null,
      _executeBy?: string | null
    ): ProposalExecutedEventFilter;
    ProposalExecuted(
      _zDAOId?: BigNumberish | null,
      _proposalId?: BigNumberish | null,
      _executeBy?: string | null
    ): ProposalExecutedEventFilter;
  };

  estimateGas: {
    addNewDAO(
      _zNA: BigNumberish,
      _zDAOConfig: IEtherZDAOChef.ZDAOConfigStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelProposal(
      _daoId: BigNumberish,
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createProposal(
      _daoId: BigNumberish,
      _target: string,
      _value: BigNumberish,
      _data: BytesLike,
      _ipfs: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    doeszDAOExistForzNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    executeProposal(
      _daoId: BigNumberish,
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getzDAOById(
      _daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getzDaoByZNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listzDAOs(
      _startIndex: BigNumberish,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberOfzDAOs(overrides?: CallOverrides): Promise<BigNumber>;

    removeDAO(
      _daoId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDAOGnosisSafe(
      _daoId: BigNumberish,
      _gnosisSafe: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDAOVotingToken(
      _daoId: BigNumberish,
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addNewDAO(
      _zNA: BigNumberish,
      _zDAOConfig: IEtherZDAOChef.ZDAOConfigStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelProposal(
      _daoId: BigNumberish,
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createProposal(
      _daoId: BigNumberish,
      _target: string,
      _value: BigNumberish,
      _data: BytesLike,
      _ipfs: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    doeszDAOExistForzNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    executeProposal(
      _daoId: BigNumberish,
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getzDAOById(
      _daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getzDaoByZNA(
      _zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listzDAOs(
      _startIndex: BigNumberish,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberOfzDAOs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeDAO(
      _daoId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeZNAAssociation(
      _daoId: BigNumberish,
      _zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDAOGnosisSafe(
      _daoId: BigNumberish,
      _gnosisSafe: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDAOVotingToken(
      _daoId: BigNumberish,
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
