/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace IEtherZDAO {
  export type ProposalStruct = {
    proposalId: BigNumberish;
    createdBy: string;
    startTimestamp: BigNumberish;
    endTimestamp: BigNumberish;
    yes: BigNumberish;
    no: BigNumberish;
    reserved: BigNumberish;
    ipfs: BytesLike;
    token: string;
    amount: BigNumberish;
    snapshot: BigNumberish;
    state: BigNumberish;
  };

  export type ProposalStructOutput = [
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    number
  ] & {
    proposalId: BigNumber;
    createdBy: string;
    startTimestamp: BigNumber;
    endTimestamp: BigNumber;
    yes: BigNumber;
    no: BigNumber;
    reserved: BigNumber;
    ipfs: string;
    token: string;
    amount: BigNumber;
    snapshot: BigNumber;
    state: number;
  };
}

export interface IEtherZDAOInterface extends utils.Interface {
  contractName: "IEtherZDAO";
  functions: {
    "createProposal(uint256,uint256,address,uint256,bytes32)": FunctionFragment;
    "destroyed()": FunctionFragment;
    "executeProposal(uint256)": FunctionFragment;
    "listProposals(uint256,uint256)": FunctionFragment;
    "numberOfProposals()": FunctionFragment;
    "setDestroyed(bool)": FunctionFragment;
    "setVoteResult(bytes)": FunctionFragment;
    "zDAOOwner()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createProposal",
    values: [BigNumberish, BigNumberish, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "destroyed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listProposals",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDestroyed",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setVoteResult",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "zDAOOwner", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "destroyed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDestroyed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVoteResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zDAOOwner", data: BytesLike): Result;

  events: {
    "ProposalCollected(uint256,uint256,uint256,uint256)": EventFragment;
    "ProposalCreated(uint256,address,uint256,uint256,uint256)": EventFragment;
    "ProposalExecuted(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProposalCollected"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalExecuted"): EventFragment;
}

export type ProposalCollectedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber],
  { _zDAOId: BigNumber; _propoalId: BigNumber; yes: BigNumber; no: BigNumber }
>;

export type ProposalCollectedEventFilter =
  TypedEventFilter<ProposalCollectedEvent>;

export type ProposalCreatedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, BigNumber],
  {
    _zDAOId: BigNumber;
    _proposalAuthor: string;
    _proposalId: BigNumber;
    _startTimestamp: BigNumber;
    _endTimestamp: BigNumber;
  }
>;

export type ProposalCreatedEventFilter = TypedEventFilter<ProposalCreatedEvent>;

export type ProposalExecutedEvent = TypedEvent<
  [BigNumber, BigNumber],
  { _zDAOId: BigNumber; _proposalId: BigNumber }
>;

export type ProposalExecutedEventFilter =
  TypedEventFilter<ProposalExecutedEvent>;

export interface IEtherZDAO extends BaseContract {
  contractName: "IEtherZDAO";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IEtherZDAOInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createProposal(
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      _token: string,
      _amount: BigNumberish,
      _ipfs: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    destroyed(overrides?: CallOverrides): Promise<[boolean]>;

    executeProposal(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    listProposals(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IEtherZDAO.ProposalStructOutput[]]>;

    numberOfProposals(overrides?: CallOverrides): Promise<[BigNumber]>;

    setDestroyed(
      _destroyed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setVoteResult(
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    zDAOOwner(overrides?: CallOverrides): Promise<[string]>;
  };

  createProposal(
    _startTimestamp: BigNumberish,
    _endTimestamp: BigNumberish,
    _token: string,
    _amount: BigNumberish,
    _ipfs: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  destroyed(overrides?: CallOverrides): Promise<boolean>;

  executeProposal(
    _proposalId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  listProposals(
    _startIndex: BigNumberish,
    _endIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IEtherZDAO.ProposalStructOutput[]>;

  numberOfProposals(overrides?: CallOverrides): Promise<BigNumber>;

  setDestroyed(
    _destroyed: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setVoteResult(
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  zDAOOwner(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createProposal(
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      _token: string,
      _amount: BigNumberish,
      _ipfs: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    destroyed(overrides?: CallOverrides): Promise<boolean>;

    executeProposal(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    listProposals(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IEtherZDAO.ProposalStructOutput[]>;

    numberOfProposals(overrides?: CallOverrides): Promise<BigNumber>;

    setDestroyed(_destroyed: boolean, overrides?: CallOverrides): Promise<void>;

    setVoteResult(_data: BytesLike, overrides?: CallOverrides): Promise<void>;

    zDAOOwner(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ProposalCollected(uint256,uint256,uint256,uint256)"(
      _zDAOId?: BigNumberish | null,
      _propoalId?: BigNumberish | null,
      yes?: null,
      no?: null
    ): ProposalCollectedEventFilter;
    ProposalCollected(
      _zDAOId?: BigNumberish | null,
      _propoalId?: BigNumberish | null,
      yes?: null,
      no?: null
    ): ProposalCollectedEventFilter;

    "ProposalCreated(uint256,address,uint256,uint256,uint256)"(
      _zDAOId?: BigNumberish | null,
      _proposalAuthor?: string | null,
      _proposalId?: BigNumberish | null,
      _startTimestamp?: null,
      _endTimestamp?: null
    ): ProposalCreatedEventFilter;
    ProposalCreated(
      _zDAOId?: BigNumberish | null,
      _proposalAuthor?: string | null,
      _proposalId?: BigNumberish | null,
      _startTimestamp?: null,
      _endTimestamp?: null
    ): ProposalCreatedEventFilter;

    "ProposalExecuted(uint256,uint256)"(
      _zDAOId?: BigNumberish | null,
      _proposalId?: BigNumberish | null
    ): ProposalExecutedEventFilter;
    ProposalExecuted(
      _zDAOId?: BigNumberish | null,
      _proposalId?: BigNumberish | null
    ): ProposalExecutedEventFilter;
  };

  estimateGas: {
    createProposal(
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      _token: string,
      _amount: BigNumberish,
      _ipfs: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    destroyed(overrides?: CallOverrides): Promise<BigNumber>;

    executeProposal(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    listProposals(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberOfProposals(overrides?: CallOverrides): Promise<BigNumber>;

    setDestroyed(
      _destroyed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setVoteResult(
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    zDAOOwner(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createProposal(
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      _token: string,
      _amount: BigNumberish,
      _ipfs: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    destroyed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executeProposal(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    listProposals(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberOfProposals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setDestroyed(
      _destroyed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setVoteResult(
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    zDAOOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
