/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ILockableInterface extends utils.Interface {
  contractName: "ILockable";
  functions: {
    "lock(address)": FunctionFragment;
    "locked(address)": FunctionFragment;
    "unlock(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "lock", values: [string]): string;
  encodeFunctionData(functionFragment: "locked", values: [string]): string;
  encodeFunctionData(functionFragment: "unlock", values: [string]): string;

  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "locked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unlock", data: BytesLike): Result;

  events: {
    "Locked(address,uint256,uint256)": EventFragment;
    "Unlocked(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Locked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unlocked"): EventFragment;
}

export type LockedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { _token: string; _amount: BigNumber; _lockedRepeat: BigNumber }
>;

export type LockedEventFilter = TypedEventFilter<LockedEvent>;

export type UnlockedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { _token: string; _amount: BigNumber; _lockedRepeat: BigNumber }
>;

export type UnlockedEventFilter = TypedEventFilter<UnlockedEvent>;

export interface ILockable extends BaseContract {
  contractName: "ILockable";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ILockableInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    lock(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    locked(_token: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    unlock(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  lock(
    _token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  locked(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

  unlock(
    _token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    lock(_token: string, overrides?: CallOverrides): Promise<void>;

    locked(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

    unlock(_token: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "Locked(address,uint256,uint256)"(
      _token?: string | null,
      _amount?: BigNumberish | null,
      _lockedRepeat?: BigNumberish | null
    ): LockedEventFilter;
    Locked(
      _token?: string | null,
      _amount?: BigNumberish | null,
      _lockedRepeat?: BigNumberish | null
    ): LockedEventFilter;

    "Unlocked(address,uint256,uint256)"(
      _token?: string | null,
      _amount?: BigNumberish | null,
      _lockedRepeat?: BigNumberish | null
    ): UnlockedEventFilter;
    Unlocked(
      _token?: string | null,
      _amount?: BigNumberish | null,
      _lockedRepeat?: BigNumberish | null
    ): UnlockedEventFilter;
  };

  estimateGas: {
    lock(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    locked(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

    unlock(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    lock(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    locked(
      _token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unlock(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
