/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace IPolyZDAO {
  export type ProposalStruct = {
    proposalId: BigNumberish;
    startTimestamp: BigNumberish;
    endTimestamp: BigNumberish;
    yes: BigNumberish;
    no: BigNumberish;
    voters: BigNumberish;
    snapshot: BigNumberish;
    collected: boolean;
    executed: boolean;
    canceled: boolean;
  };

  export type ProposalStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean,
    boolean,
    boolean
  ] & {
    proposalId: BigNumber;
    startTimestamp: BigNumber;
    endTimestamp: BigNumber;
    yes: BigNumber;
    no: BigNumber;
    voters: BigNumber;
    snapshot: BigNumber;
    collected: boolean;
    executed: boolean;
    canceled: boolean;
  };
}

export interface IPolyZDAOInterface extends utils.Interface {
  contractName: "IPolyZDAO";
  functions: {
    "__ZDAO_init(address,address,uint256,uint256)": FunctionFragment;
    "canCollectProposal(uint256)": FunctionFragment;
    "canVote(uint256,address)": FunctionFragment;
    "cancelProposal(uint256)": FunctionFragment;
    "choiceOfVoter(uint256,address)": FunctionFragment;
    "collectProposal(uint256)": FunctionFragment;
    "createProposal(uint256,uint256)": FunctionFragment;
    "destroyed()": FunctionFragment;
    "executeProposal(uint256)": FunctionFragment;
    "listProposals(uint256,uint256)": FunctionFragment;
    "listVoters(uint256,uint256,uint256)": FunctionFragment;
    "numberOfProposals()": FunctionFragment;
    "setDestroyed(bool)": FunctionFragment;
    "state(uint256)": FunctionFragment;
    "vote(uint256,address,uint256)": FunctionFragment;
    "votesResultOfProposal(uint256)": FunctionFragment;
    "votingPowerOfVoter(uint256,address)": FunctionFragment;
    "zDAOId()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "__ZDAO_init",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canCollectProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canVote",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "choiceOfVoter",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "collectProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "destroyed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listProposals",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listVoters",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDestroyed",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "state", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votesResultOfProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votingPowerOfVoter",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "zDAOId", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "__ZDAO_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canCollectProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "choiceOfVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "destroyed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listVoters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numberOfProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDestroyed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votesResultOfProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingPowerOfVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zDAOId", data: BytesLike): Result;

  events: {};
}

export interface IPolyZDAO extends BaseContract {
  contractName: "IPolyZDAO";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPolyZDAOInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    __ZDAO_init(
      _zDAOChef: string,
      _staking: string,
      _zDAOId: BigNumberish,
      _duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    canCollectProposal(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    canVote(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    cancelProposal(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    choiceOfVoter(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    collectProposal(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createProposal(
      _proposalId: BigNumberish,
      _startTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    destroyed(overrides?: CallOverrides): Promise<[boolean]>;

    executeProposal(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    listProposals(
      _startIndex: BigNumberish,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [IPolyZDAO.ProposalStructOutput[]] & {
        records: IPolyZDAO.ProposalStructOutput[];
      }
    >;

    listVoters(
      _proposalId: BigNumberish,
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[], BigNumber[]] & {
        voters: string[];
        choices: BigNumber[];
        votes: BigNumber[];
      }
    >;

    numberOfProposals(overrides?: CallOverrides): Promise<[BigNumber]>;

    setDestroyed(
      _destroyed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    state(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    vote(
      _proposalId: BigNumberish,
      _voter: string,
      _choice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    votesResultOfProposal(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        voters: BigNumber;
        yes: BigNumber;
        no: BigNumber;
      }
    >;

    votingPowerOfVoter(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    zDAOId(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  __ZDAO_init(
    _zDAOChef: string,
    _staking: string,
    _zDAOId: BigNumberish,
    _duration: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  canCollectProposal(
    _proposalId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  canVote(
    _proposalId: BigNumberish,
    _voter: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  cancelProposal(
    _proposalId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  choiceOfVoter(
    _proposalId: BigNumberish,
    _voter: string,
    overrides?: CallOverrides
  ): Promise<number>;

  collectProposal(
    _proposalId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createProposal(
    _proposalId: BigNumberish,
    _startTimestamp: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  destroyed(overrides?: CallOverrides): Promise<boolean>;

  executeProposal(
    _proposalId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  listProposals(
    _startIndex: BigNumberish,
    _count: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IPolyZDAO.ProposalStructOutput[]>;

  listVoters(
    _proposalId: BigNumberish,
    _startIndex: BigNumberish,
    _endIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string[], BigNumber[], BigNumber[]] & {
      voters: string[];
      choices: BigNumber[];
      votes: BigNumber[];
    }
  >;

  numberOfProposals(overrides?: CallOverrides): Promise<BigNumber>;

  setDestroyed(
    _destroyed: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  state(_proposalId: BigNumberish, overrides?: CallOverrides): Promise<number>;

  vote(
    _proposalId: BigNumberish,
    _voter: string,
    _choice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  votesResultOfProposal(
    _proposalId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      voters: BigNumber;
      yes: BigNumber;
      no: BigNumber;
    }
  >;

  votingPowerOfVoter(
    _proposalId: BigNumberish,
    _voter: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  zDAOId(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    __ZDAO_init(
      _zDAOChef: string,
      _staking: string,
      _zDAOId: BigNumberish,
      _duration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    canCollectProposal(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    canVote(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    cancelProposal(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    choiceOfVoter(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<number>;

    collectProposal(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        voters: BigNumber;
        yes: BigNumber;
        no: BigNumber;
      }
    >;

    createProposal(
      _proposalId: BigNumberish,
      _startTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    destroyed(overrides?: CallOverrides): Promise<boolean>;

    executeProposal(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    listProposals(
      _startIndex: BigNumberish,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IPolyZDAO.ProposalStructOutput[]>;

    listVoters(
      _proposalId: BigNumberish,
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[], BigNumber[]] & {
        voters: string[];
        choices: BigNumber[];
        votes: BigNumber[];
      }
    >;

    numberOfProposals(overrides?: CallOverrides): Promise<BigNumber>;

    setDestroyed(_destroyed: boolean, overrides?: CallOverrides): Promise<void>;

    state(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    vote(
      _proposalId: BigNumberish,
      _voter: string,
      _choice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    votesResultOfProposal(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        voters: BigNumber;
        yes: BigNumber;
        no: BigNumber;
      }
    >;

    votingPowerOfVoter(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    zDAOId(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    __ZDAO_init(
      _zDAOChef: string,
      _staking: string,
      _zDAOId: BigNumberish,
      _duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    canCollectProposal(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    canVote(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelProposal(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    choiceOfVoter(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collectProposal(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createProposal(
      _proposalId: BigNumberish,
      _startTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    destroyed(overrides?: CallOverrides): Promise<BigNumber>;

    executeProposal(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    listProposals(
      _startIndex: BigNumberish,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listVoters(
      _proposalId: BigNumberish,
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberOfProposals(overrides?: CallOverrides): Promise<BigNumber>;

    setDestroyed(
      _destroyed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    state(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vote(
      _proposalId: BigNumberish,
      _voter: string,
      _choice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    votesResultOfProposal(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    votingPowerOfVoter(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    zDAOId(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    __ZDAO_init(
      _zDAOChef: string,
      _staking: string,
      _zDAOId: BigNumberish,
      _duration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    canCollectProposal(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    canVote(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelProposal(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    choiceOfVoter(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collectProposal(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createProposal(
      _proposalId: BigNumberish,
      _startTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    destroyed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executeProposal(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    listProposals(
      _startIndex: BigNumberish,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listVoters(
      _proposalId: BigNumberish,
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberOfProposals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setDestroyed(
      _destroyed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    state(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vote(
      _proposalId: BigNumberish,
      _voter: string,
      _choice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    votesResultOfProposal(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    votingPowerOfVoter(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    zDAOId(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
