/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IPolyZDAOChefInterface extends utils.Interface {
  contractName: "IPolyZDAOChef";
  functions: {
    "getzDAOById(uint256)": FunctionFragment;
    "listzDAOs(uint256,uint256)": FunctionFragment;
    "numberOfzDAOs()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getzDAOById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listzDAOs",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfzDAOs",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getzDAOById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listzDAOs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numberOfzDAOs",
    data: BytesLike
  ): Result;

  events: {
    "DAOCreated(address,uint256,address,bool,uint256)": EventFragment;
    "DAODestroyed(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DAOCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DAODestroyed"): EventFragment;
}

export type DAOCreatedEvent = TypedEvent<
  [string, BigNumber, string, boolean, BigNumber],
  {
    _zDAO: string;
    _daoId: BigNumber;
    _token: string;
    _isRelativeMajority: boolean;
    _threshold: BigNumber;
  }
>;

export type DAOCreatedEventFilter = TypedEventFilter<DAOCreatedEvent>;

export type DAODestroyedEvent = TypedEvent<[BigNumber], { _daoId: BigNumber }>;

export type DAODestroyedEventFilter = TypedEventFilter<DAODestroyedEvent>;

export interface IPolyZDAOChef extends BaseContract {
  contractName: "IPolyZDAOChef";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPolyZDAOChefInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getzDAOById(
      _daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    listzDAOs(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    numberOfzDAOs(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  getzDAOById(_daoId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  listzDAOs(
    _startIndex: BigNumberish,
    _endIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  numberOfzDAOs(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    getzDAOById(
      _daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    listzDAOs(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    numberOfzDAOs(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "DAOCreated(address,uint256,address,bool,uint256)"(
      _zDAO?: string | null,
      _daoId?: BigNumberish | null,
      _token?: string | null,
      _isRelativeMajority?: null,
      _threshold?: null
    ): DAOCreatedEventFilter;
    DAOCreated(
      _zDAO?: string | null,
      _daoId?: BigNumberish | null,
      _token?: string | null,
      _isRelativeMajority?: null,
      _threshold?: null
    ): DAOCreatedEventFilter;

    "DAODestroyed(uint256)"(
      _daoId?: BigNumberish | null
    ): DAODestroyedEventFilter;
    DAODestroyed(_daoId?: BigNumberish | null): DAODestroyedEventFilter;
  };

  estimateGas: {
    getzDAOById(
      _daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listzDAOs(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberOfzDAOs(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getzDAOById(
      _daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listzDAOs(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberOfzDAOs(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
