/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace IPolyZDAO {
  export type ProposalStruct = {
    proposalId: BigNumberish;
    startTimestamp: BigNumberish;
    endTimestamp: BigNumberish;
    yes: BigNumberish;
    no: BigNumberish;
    reserved: BigNumberish;
    snapshot: BigNumberish;
    state: BigNumberish;
  };

  export type ProposalStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number
  ] & {
    proposalId: BigNumber;
    startTimestamp: BigNumber;
    endTimestamp: BigNumber;
    yes: BigNumber;
    no: BigNumber;
    reserved: BigNumber;
    snapshot: BigNumber;
    state: number;
  };
}

export interface IPolyZDAOInterface extends utils.Interface {
  contractName: "IPolyZDAO";
  functions: {
    "canCollectResult(uint256)": FunctionFragment;
    "canVote(uint256,address)": FunctionFragment;
    "collectResult(uint256)": FunctionFragment;
    "createProposal(uint256,uint256,uint256)": FunctionFragment;
    "destroyed()": FunctionFragment;
    "getVoterChoice(uint256,address)": FunctionFragment;
    "listProposals(uint256,uint256)": FunctionFragment;
    "numberOfProposals()": FunctionFragment;
    "setDestroyed(bool)": FunctionFragment;
    "vote(uint256,uint8)": FunctionFragment;
    "zDAOId()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "canCollectResult",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canVote",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "collectResult",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "destroyed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getVoterChoice",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "listProposals",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "numberOfProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDestroyed",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "zDAOId", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "canCollectResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "destroyed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVoterChoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberOfProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDestroyed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "zDAOId", data: BytesLike): Result;

  events: {
    "CastVote(uint256,uint256,address,uint256)": EventFragment;
    "CollectResult(uint256,uint256,uint256,uint256)": EventFragment;
    "ProposalCreated(uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CastVote"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CollectResult"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalCreated"): EventFragment;
}

export type CastVoteEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber],
  {
    _zDAOId: BigNumber;
    _proposalId: BigNumber;
    _voter: string;
    _choice: BigNumber;
  }
>;

export type CastVoteEventFilter = TypedEventFilter<CastVoteEvent>;

export type CollectResultEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber],
  { _zDAOId: BigNumber; _proposalId: BigNumber; yes: BigNumber; no: BigNumber }
>;

export type CollectResultEventFilter = TypedEventFilter<CollectResultEvent>;

export type ProposalCreatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber],
  {
    _zDAOId: BigNumber;
    _proposalId: BigNumber;
    _startTimestamp: BigNumber;
    _endTimestamp: BigNumber;
  }
>;

export type ProposalCreatedEventFilter = TypedEventFilter<ProposalCreatedEvent>;

export interface IPolyZDAO extends BaseContract {
  contractName: "IPolyZDAO";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPolyZDAOInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    canCollectResult(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    canVote(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    collectResult(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createProposal(
      _proposalId: BigNumberish,
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    destroyed(overrides?: CallOverrides): Promise<[boolean]>;

    getVoterChoice(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    listProposals(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IPolyZDAO.ProposalStructOutput[]]>;

    numberOfProposals(overrides?: CallOverrides): Promise<[BigNumber]>;

    setDestroyed(
      _destroyed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    vote(
      _proposalId: BigNumberish,
      _choice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    zDAOId(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  canCollectResult(
    _proposalId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  canVote(
    _proposalId: BigNumberish,
    _voter: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  collectResult(
    _proposalId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createProposal(
    _proposalId: BigNumberish,
    _startTimestamp: BigNumberish,
    _endTimestamp: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  destroyed(overrides?: CallOverrides): Promise<boolean>;

  getVoterChoice(
    _proposalId: BigNumberish,
    _voter: string,
    overrides?: CallOverrides
  ): Promise<number>;

  listProposals(
    _startIndex: BigNumberish,
    _endIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IPolyZDAO.ProposalStructOutput[]>;

  numberOfProposals(overrides?: CallOverrides): Promise<BigNumber>;

  setDestroyed(
    _destroyed: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  vote(
    _proposalId: BigNumberish,
    _choice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  zDAOId(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    canCollectResult(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    canVote(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    collectResult(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createProposal(
      _proposalId: BigNumberish,
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    destroyed(overrides?: CallOverrides): Promise<boolean>;

    getVoterChoice(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<number>;

    listProposals(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IPolyZDAO.ProposalStructOutput[]>;

    numberOfProposals(overrides?: CallOverrides): Promise<BigNumber>;

    setDestroyed(_destroyed: boolean, overrides?: CallOverrides): Promise<void>;

    vote(
      _proposalId: BigNumberish,
      _choice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    zDAOId(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "CastVote(uint256,uint256,address,uint256)"(
      _zDAOId?: BigNumberish | null,
      _proposalId?: BigNumberish | null,
      _voter?: string | null,
      _choice?: null
    ): CastVoteEventFilter;
    CastVote(
      _zDAOId?: BigNumberish | null,
      _proposalId?: BigNumberish | null,
      _voter?: string | null,
      _choice?: null
    ): CastVoteEventFilter;

    "CollectResult(uint256,uint256,uint256,uint256)"(
      _zDAOId?: BigNumberish | null,
      _proposalId?: BigNumberish | null,
      yes?: null,
      no?: null
    ): CollectResultEventFilter;
    CollectResult(
      _zDAOId?: BigNumberish | null,
      _proposalId?: BigNumberish | null,
      yes?: null,
      no?: null
    ): CollectResultEventFilter;

    "ProposalCreated(uint256,uint256,uint256,uint256)"(
      _zDAOId?: BigNumberish | null,
      _proposalId?: BigNumberish | null,
      _startTimestamp?: null,
      _endTimestamp?: null
    ): ProposalCreatedEventFilter;
    ProposalCreated(
      _zDAOId?: BigNumberish | null,
      _proposalId?: BigNumberish | null,
      _startTimestamp?: null,
      _endTimestamp?: null
    ): ProposalCreatedEventFilter;
  };

  estimateGas: {
    canCollectResult(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    canVote(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collectResult(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createProposal(
      _proposalId: BigNumberish,
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    destroyed(overrides?: CallOverrides): Promise<BigNumber>;

    getVoterChoice(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    listProposals(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberOfProposals(overrides?: CallOverrides): Promise<BigNumber>;

    setDestroyed(
      _destroyed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    vote(
      _proposalId: BigNumberish,
      _choice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    zDAOId(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    canCollectResult(
      _proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    canVote(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collectResult(
      _proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createProposal(
      _proposalId: BigNumberish,
      _startTimestamp: BigNumberish,
      _endTimestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    destroyed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getVoterChoice(
      _proposalId: BigNumberish,
      _voter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listProposals(
      _startIndex: BigNumberish,
      _endIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberOfProposals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setDestroyed(
      _destroyed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    vote(
      _proposalId: BigNumberish,
      _choice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    zDAOId(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
