/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IStakingInterface extends utils.Interface {
  contractName: "IStaking";
  functions: {
    "stakeERC20(address,uint256)": FunctionFragment;
    "stakeERC721(address,uint256)": FunctionFragment;
    "totalStaked(address)": FunctionFragment;
    "unstakeERC20(address,uint256)": FunctionFragment;
    "unstakeERC721(address,uint256)": FunctionFragment;
    "userStaked(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "stakeERC20",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeERC721",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "totalStaked", values: [string]): string;
  encodeFunctionData(
    functionFragment: "unstakeERC20",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeERC721",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userStaked",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "stakeERC20", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userStaked", data: BytesLike): Result;

  events: {
    "StakedERC20(address,address,uint256,uint256)": EventFragment;
    "StakedERC721(address,address,uint256,uint256)": EventFragment;
    "UnstakedERC20(address,address,uint256,uint256)": EventFragment;
    "UnstakedERC721(address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "StakedERC20"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakedERC721"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnstakedERC20"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnstakedERC721"): EventFragment;
}

export type StakedERC20Event = TypedEvent<
  [string, string, BigNumber, BigNumber],
  {
    _user: string;
    _token: string;
    _amount: BigNumber;
    _totalPerUser: BigNumber;
  }
>;

export type StakedERC20EventFilter = TypedEventFilter<StakedERC20Event>;

export type StakedERC721Event = TypedEvent<
  [string, string, BigNumber, BigNumber],
  {
    _user: string;
    _token: string;
    _tokenId: BigNumber;
    _totalPerUser: BigNumber;
  }
>;

export type StakedERC721EventFilter = TypedEventFilter<StakedERC721Event>;

export type UnstakedERC20Event = TypedEvent<
  [string, string, BigNumber, BigNumber],
  {
    _user: string;
    _token: string;
    _amount: BigNumber;
    _totalPerUser: BigNumber;
  }
>;

export type UnstakedERC20EventFilter = TypedEventFilter<UnstakedERC20Event>;

export type UnstakedERC721Event = TypedEvent<
  [string, string, BigNumber, BigNumber],
  {
    _user: string;
    _token: string;
    _tokenId: BigNumber;
    _totalPerUser: BigNumber;
  }
>;

export type UnstakedERC721EventFilter = TypedEventFilter<UnstakedERC721Event>;

export interface IStaking extends BaseContract {
  contractName: "IStaking";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IStakingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    stakeERC20(
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stakeERC721(
      _token: string,
      _tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totalStaked(
      _token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    unstakeERC20(
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unstakeERC721(
      _token: string,
      _tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    userStaked(
      _user: string,
      _token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  stakeERC20(
    _token: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stakeERC721(
    _token: string,
    _tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totalStaked(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

  unstakeERC20(
    _token: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unstakeERC721(
    _token: string,
    _tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  userStaked(
    _user: string,
    _token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    stakeERC20(
      _token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    stakeERC721(
      _token: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    totalStaked(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

    unstakeERC20(
      _token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    unstakeERC721(
      _token: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    userStaked(
      _user: string,
      _token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "StakedERC20(address,address,uint256,uint256)"(
      _user?: string | null,
      _token?: string | null,
      _amount?: BigNumberish | null,
      _totalPerUser?: null
    ): StakedERC20EventFilter;
    StakedERC20(
      _user?: string | null,
      _token?: string | null,
      _amount?: BigNumberish | null,
      _totalPerUser?: null
    ): StakedERC20EventFilter;

    "StakedERC721(address,address,uint256,uint256)"(
      _user?: string | null,
      _token?: string | null,
      _tokenId?: BigNumberish | null,
      _totalPerUser?: null
    ): StakedERC721EventFilter;
    StakedERC721(
      _user?: string | null,
      _token?: string | null,
      _tokenId?: BigNumberish | null,
      _totalPerUser?: null
    ): StakedERC721EventFilter;

    "UnstakedERC20(address,address,uint256,uint256)"(
      _user?: string | null,
      _token?: string | null,
      _amount?: BigNumberish | null,
      _totalPerUser?: null
    ): UnstakedERC20EventFilter;
    UnstakedERC20(
      _user?: string | null,
      _token?: string | null,
      _amount?: BigNumberish | null,
      _totalPerUser?: null
    ): UnstakedERC20EventFilter;

    "UnstakedERC721(address,address,uint256,uint256)"(
      _user?: string | null,
      _token?: string | null,
      _tokenId?: BigNumberish | null,
      _totalPerUser?: null
    ): UnstakedERC721EventFilter;
    UnstakedERC721(
      _user?: string | null,
      _token?: string | null,
      _tokenId?: BigNumberish | null,
      _totalPerUser?: null
    ): UnstakedERC721EventFilter;
  };

  estimateGas: {
    stakeERC20(
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stakeERC721(
      _token: string,
      _tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totalStaked(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

    unstakeERC20(
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unstakeERC721(
      _token: string,
      _tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    userStaked(
      _user: string,
      _token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    stakeERC20(
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stakeERC721(
      _token: string,
      _tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totalStaked(
      _token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unstakeERC20(
      _token: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unstakeERC721(
      _token: string,
      _tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    userStaked(
      _user: string,
      _token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
