/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ZDAOCoreInterface extends ethers.utils.Interface {
  functions: {
    "addNewDAO(uint256,address)": FunctionFragment;
    "addZNAAssociation(uint256,uint256)": FunctionFragment;
    "ensPresence(uint256)": FunctionFragment;
    "getDAOZNAs(uint256)": FunctionFragment;
    "getEnsHashes()": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "removeZNAAssociation(uint256,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "zNATozDAO(uint256)": FunctionFragment;
    "znsHub()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addNewDAO",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addZNAAssociation",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ensPresence",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDAOZNAs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEnsHashes",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeZNAAssociation",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "zNATozDAO",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "znsHub", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addNewDAO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addZNAAssociation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ensPresence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDAOZNAs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEnsHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeZNAAssociation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zNATozDAO", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "znsHub", data: BytesLike): Result;

  events: {
    "DAOCreated(uint256,uint256)": EventFragment;
    "LinkAdded(uint256,uint256)": EventFragment;
    "LinkRemoved(uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DAOCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LinkAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LinkRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class ZDAOCore extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ZDAOCoreInterface;

  functions: {
    addNewDAO(
      ens: BigNumberish,
      gnosis: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addZNAAssociation(
      daoId: BigNumberish,
      zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ensPresence(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getDAOZNAs(
      daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getEnsHashes(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    initialize(
      _znsHub: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    removeZNAAssociation(
      daoId: BigNumberish,
      zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    zNATozDAO(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    znsHub(overrides?: CallOverrides): Promise<[string]>;
  };

  addNewDAO(
    ens: BigNumberish,
    gnosis: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addZNAAssociation(
    daoId: BigNumberish,
    zNA: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ensPresence(arg0: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  getDAOZNAs(
    daoId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getEnsHashes(overrides?: CallOverrides): Promise<BigNumber[]>;

  initialize(
    _znsHub: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  removeZNAAssociation(
    daoId: BigNumberish,
    zNA: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  zNATozDAO(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  znsHub(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addNewDAO(
      ens: BigNumberish,
      gnosis: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addZNAAssociation(
      daoId: BigNumberish,
      zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    ensPresence(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getDAOZNAs(
      daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getEnsHashes(overrides?: CallOverrides): Promise<BigNumber[]>;

    initialize(_znsHub: string, overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    removeZNAAssociation(
      daoId: BigNumberish,
      zNA: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    zNATozDAO(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    znsHub(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    DAOCreated(
      daoId?: BigNumberish | null,
      ens?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { daoId: BigNumber; ens: BigNumber }
    >;

    LinkAdded(
      daoId?: BigNumberish | null,
      zNA?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { daoId: BigNumber; zNA: BigNumber }
    >;

    LinkRemoved(
      daoId?: BigNumberish | null,
      zNA?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { daoId: BigNumber; zNA: BigNumber }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    addNewDAO(
      ens: BigNumberish,
      gnosis: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addZNAAssociation(
      daoId: BigNumberish,
      zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ensPresence(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDAOZNAs(
      daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEnsHashes(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _znsHub: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    removeZNAAssociation(
      daoId: BigNumberish,
      zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    zNATozDAO(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    znsHub(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addNewDAO(
      ens: BigNumberish,
      gnosis: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addZNAAssociation(
      daoId: BigNumberish,
      zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ensPresence(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDAOZNAs(
      daoId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEnsHashes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _znsHub: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeZNAAssociation(
      daoId: BigNumberish,
      zNA: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    zNATozDAO(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    znsHub(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
