/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ZDAOCoreInterface extends ethers.utils.Interface {
  functions: {
    "addNewDAO(string,string,address[])": FunctionFragment;
    "addZNAAssociation(string,string)": FunctionFragment;
    "getDAOIds()": FunctionFragment;
    "getDAOMetadataUri(string)": FunctionFragment;
    "getDAOZNAs(string)": FunctionFragment;
    "owner()": FunctionFragment;
    "removeZNAAssociation(string,string)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setDAOAdmin(string,address,bool)": FunctionFragment;
    "setDAOMetadataUri(string,string)": FunctionFragment;
    "setManager(address,bool)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "zDAOIDPresence(string)": FunctionFragment;
    "zNATozDAO(string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addNewDAO",
    values: [string, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addZNAAssociation",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "getDAOIds", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDAOMetadataUri",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getDAOZNAs", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeZNAAssociation",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDAOAdmin",
    values: [string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDAOMetadataUri",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setManager",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "zDAOIDPresence",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "zNATozDAO", values: [string]): string;

  decodeFunctionResult(functionFragment: "addNewDAO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addZNAAssociation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDAOIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDAOMetadataUri",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDAOZNAs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeZNAAssociation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDAOAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDAOMetadataUri",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setManager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zDAOIDPresence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "zNATozDAO", data: BytesLike): Result;

  events: {
    "DAOCreated(string,string)": EventFragment;
    "DAOzNAAdded(string,string)": EventFragment;
    "DAOzNARemoved(string,string)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DAOCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DAOzNAAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DAOzNARemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class ZDAOCore extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ZDAOCoreInterface;

  functions: {
    addNewDAO(
      daoId: string,
      metadataUri: string,
      admins: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addZNAAssociation(
      daoId: string,
      zNA: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getDAOIds(overrides?: CallOverrides): Promise<[string[]]>;

    getDAOMetadataUri(
      daoId: string,
      overrides?: CallOverrides
    ): Promise<[string] & { metadataUri: string }>;

    getDAOZNAs(daoId: string, overrides?: CallOverrides): Promise<[string[]]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    removeZNAAssociation(
      daoId: string,
      zNA: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDAOAdmin(
      daoId: string,
      admin: string,
      flag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDAOMetadataUri(
      daoId: string,
      metadataUri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setManager(
      manager: string,
      allowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    zDAOIDPresence(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    zNATozDAO(arg0: string, overrides?: CallOverrides): Promise<[string]>;
  };

  addNewDAO(
    daoId: string,
    metadataUri: string,
    admins: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addZNAAssociation(
    daoId: string,
    zNA: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getDAOIds(overrides?: CallOverrides): Promise<string[]>;

  getDAOMetadataUri(daoId: string, overrides?: CallOverrides): Promise<string>;

  getDAOZNAs(daoId: string, overrides?: CallOverrides): Promise<string[]>;

  owner(overrides?: CallOverrides): Promise<string>;

  removeZNAAssociation(
    daoId: string,
    zNA: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDAOAdmin(
    daoId: string,
    admin: string,
    flag: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDAOMetadataUri(
    daoId: string,
    metadataUri: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setManager(
    manager: string,
    allowed: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  zDAOIDPresence(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  zNATozDAO(arg0: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addNewDAO(
      daoId: string,
      metadataUri: string,
      admins: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    addZNAAssociation(
      daoId: string,
      zNA: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getDAOIds(overrides?: CallOverrides): Promise<string[]>;

    getDAOMetadataUri(
      daoId: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getDAOZNAs(daoId: string, overrides?: CallOverrides): Promise<string[]>;

    owner(overrides?: CallOverrides): Promise<string>;

    removeZNAAssociation(
      daoId: string,
      zNA: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setDAOAdmin(
      daoId: string,
      admin: string,
      flag: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setDAOMetadataUri(
      daoId: string,
      metadataUri: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setManager(
      manager: string,
      allowed: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    zDAOIDPresence(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    zNATozDAO(arg0: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    DAOCreated(
      daoId?: string | null,
      metadataUri?: string | null
    ): TypedEventFilter<
      [string, string],
      { daoId: string; metadataUri: string }
    >;

    DAOzNAAdded(
      daoId?: string | null,
      zNA?: string | null
    ): TypedEventFilter<[string, string], { daoId: string; zNA: string }>;

    DAOzNARemoved(
      daoId?: string | null,
      zNA?: string | null
    ): TypedEventFilter<[string, string], { daoId: string; zNA: string }>;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    addNewDAO(
      daoId: string,
      metadataUri: string,
      admins: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addZNAAssociation(
      daoId: string,
      zNA: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getDAOIds(overrides?: CallOverrides): Promise<BigNumber>;

    getDAOMetadataUri(
      daoId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDAOZNAs(daoId: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    removeZNAAssociation(
      daoId: string,
      zNA: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDAOAdmin(
      daoId: string,
      admin: string,
      flag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDAOMetadataUri(
      daoId: string,
      metadataUri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setManager(
      manager: string,
      allowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    zDAOIDPresence(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    zNATozDAO(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addNewDAO(
      daoId: string,
      metadataUri: string,
      admins: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addZNAAssociation(
      daoId: string,
      zNA: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getDAOIds(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDAOMetadataUri(
      daoId: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDAOZNAs(
      daoId: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeZNAAssociation(
      daoId: string,
      zNA: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDAOAdmin(
      daoId: string,
      admin: string,
      flag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDAOMetadataUri(
      daoId: string,
      metadataUri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setManager(
      manager: string,
      allowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    zDAOIDPresence(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    zNATozDAO(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
