/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IChildStateSender,
  IChildStateSenderInterface,
} from "../IChildStateSender";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "sendMessageToRoot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IChildStateSender__factory {
  static readonly abi = _abi;
  static createInterface(): IChildStateSenderInterface {
    return new utils.Interface(_abi) as IChildStateSenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChildStateSender {
    return new Contract(address, _abi, signerOrProvider) as IChildStateSender;
  }
}
