/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IChildStateReceiver,
  IChildStateReceiverInterface,
} from "../IChildStateReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "processMessageFromRoot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IChildStateReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IChildStateReceiverInterface {
    return new utils.Interface(_abi) as IChildStateReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChildStateReceiver {
    return new Contract(address, _abi, signerOrProvider) as IChildStateReceiver;
  }
}
