/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IChildTunnel, IChildTunnelInterface } from "../IChildTunnel";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "sendMessageToRoot",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IChildTunnel__factory {
  static readonly abi = _abi;
  static createInterface(): IChildTunnelInterface {
    return new utils.Interface(_abi) as IChildTunnelInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChildTunnel {
    return new Contract(address, _abi, signerOrProvider) as IChildTunnel;
  }
}
