/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IEtherZDAOChef,
  IEtherZDAOChefInterface,
} from "../IEtherZDAOChef";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_creator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_zDAO",
        type: "address",
      },
    ],
    name: "DAOCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
    ],
    name: "DAODestroyed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_gnosisSafe",
        type: "address",
      },
    ],
    name: "DAOUpdateGnosisSafe",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "DAOUpdateVotingtoken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_zNA",
        type: "uint256",
      },
    ],
    name: "LinkAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_zNA",
        type: "uint256",
      },
    ],
    name: "LinkRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_zDAOId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_proposalId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_cancelBy",
        type: "address",
      },
    ],
    name: "ProposalCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_zDAOId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_propoalId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_voters",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_yes",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_no",
        type: "uint256",
      },
    ],
    name: "ProposalCollected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_zDAOId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_proposalId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_createdBy",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_snapshot",
        type: "uint256",
      },
    ],
    name: "ProposalCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_zDAOId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_proposalId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_executeBy",
        type: "address",
      },
    ],
    name: "ProposalExecuted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_zNA",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "string",
            name: "title",
            type: "string",
          },
          {
            internalType: "address",
            name: "gnosisSafe",
            type: "address",
          },
          {
            internalType: "address",
            name: "token",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "duration",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "votingThreshold",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minimumVotingParticipants",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minimumTotalVotingTokens",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isRelativeMajority",
            type: "bool",
          },
        ],
        internalType: "struct IEtherZDAOChef.ZDAOConfig",
        name: "_zDAOConfig",
        type: "tuple",
      },
    ],
    name: "addNewDAO",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_zNA",
        type: "uint256",
      },
    ],
    name: "addZNAAssociation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_proposalId",
        type: "uint256",
      },
    ],
    name: "cancelProposal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_target",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
      {
        internalType: "string",
        name: "_ipfs",
        type: "string",
      },
    ],
    name: "createProposal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_zNA",
        type: "uint256",
      },
    ],
    name: "doeszDAOExistForzNA",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_proposalId",
        type: "uint256",
      },
    ],
    name: "executeProposal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
    ],
    name: "getzDAOById",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "contract IEtherZDAO",
            name: "zDAO",
            type: "address",
          },
          {
            internalType: "uint256[]",
            name: "associatedzNAs",
            type: "uint256[]",
          },
        ],
        internalType: "struct IEtherZDAOChef.ZDAORecord",
        name: "records",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_zNA",
        type: "uint256",
      },
    ],
    name: "getzDaoByZNA",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "contract IEtherZDAO",
            name: "zDAO",
            type: "address",
          },
          {
            internalType: "uint256[]",
            name: "associatedzNAs",
            type: "uint256[]",
          },
        ],
        internalType: "struct IEtherZDAOChef.ZDAORecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_startIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_count",
        type: "uint256",
      },
    ],
    name: "listzDAOs",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "contract IEtherZDAO",
            name: "zDAO",
            type: "address",
          },
          {
            internalType: "uint256[]",
            name: "associatedzNAs",
            type: "uint256[]",
          },
        ],
        internalType: "struct IEtherZDAOChef.ZDAORecord[]",
        name: "records",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "numberOfzDAOs",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
    ],
    name: "removeDAO",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_zNA",
        type: "uint256",
      },
    ],
    name: "removeZNAAssociation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_gnosisSafe",
        type: "address",
      },
    ],
    name: "setDAOGnosisSafe",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "setDAOVotingToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IEtherZDAOChef__factory {
  static readonly abi = _abi;
  static createInterface(): IEtherZDAOChefInterface {
    return new utils.Interface(_abi) as IEtherZDAOChefInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEtherZDAOChef {
    return new Contract(address, _abi, signerOrProvider) as IEtherZDAOChef;
  }
}
