/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IEtherZDAOChef,
  IEtherZDAOChefInterface,
} from "../IEtherZDAOChef";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_creator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_zDAO",
        type: "address",
      },
    ],
    name: "DAOCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
    ],
    name: "DAODestroyed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_zNA",
        type: "uint256",
      },
    ],
    name: "LinkAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_zNA",
        type: "uint256",
      },
    ],
    name: "LinkRemoved",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_zNA",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "address",
            name: "gnosisSafe",
            type: "address",
          },
          {
            internalType: "contract IERC20Upgradeable",
            name: "token",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minPeriod",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isRelativeMajority",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "threshold",
            type: "uint256",
          },
        ],
        internalType: "struct IEtherZDAOChef.ZDAOConfig",
        name: "_zDAOConfig",
        type: "tuple",
      },
    ],
    name: "addNewDAO",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_zNA",
        type: "uint256",
      },
    ],
    name: "addZNAAssociation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_zNA",
        type: "uint256",
      },
    ],
    name: "doeszDAOExistForzNA",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
    ],
    name: "getzDAOById",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "contract IEtherZDAO",
            name: "zDAO",
            type: "address",
          },
          {
            internalType: "uint256[]",
            name: "associatedzNAs",
            type: "uint256[]",
          },
        ],
        internalType: "struct IEtherZDAOChef.ZDAORecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_zNA",
        type: "uint256",
      },
    ],
    name: "getzDaoByZNA",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "contract IEtherZDAO",
            name: "zDAO",
            type: "address",
          },
          {
            internalType: "uint256[]",
            name: "associatedzNAs",
            type: "uint256[]",
          },
        ],
        internalType: "struct IEtherZDAOChef.ZDAORecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_startIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_endIndex",
        type: "uint256",
      },
    ],
    name: "listzDAOs",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "contract IEtherZDAO",
            name: "zDAO",
            type: "address",
          },
          {
            internalType: "uint256[]",
            name: "associatedzNAs",
            type: "uint256[]",
          },
        ],
        internalType: "struct IEtherZDAOChef.ZDAORecord[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "numberOfzDAOs",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
    ],
    name: "removeDAO",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_zNA",
        type: "uint256",
      },
    ],
    name: "removeZNAAssociation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IEtherZDAOChef__factory {
  static readonly abi = _abi;
  static createInterface(): IEtherZDAOChefInterface {
    return new utils.Interface(_abi) as IEtherZDAOChefInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEtherZDAOChef {
    return new Contract(address, _abi, signerOrProvider) as IEtherZDAOChef;
  }
}
