/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IEtherZDAO, IEtherZDAOInterface } from "../IEtherZDAO";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_zDAOChef",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_zDAOId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_createdBy",
        type: "address",
      },
      {
        components: [
          {
            internalType: "string",
            name: "title",
            type: "string",
          },
          {
            internalType: "address",
            name: "gnosisSafe",
            type: "address",
          },
          {
            internalType: "address",
            name: "token",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "duration",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "votingThreshold",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minimumVotingParticipants",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minimumTotalVotingTokens",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isRelativeMajority",
            type: "bool",
          },
        ],
        internalType: "struct IEtherZDAOChef.ZDAOConfig",
        name: "_zDAOConfig",
        type: "tuple",
      },
    ],
    name: "__ZDAO_init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_cancelBy",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_proposalid",
        type: "uint256",
      },
    ],
    name: "cancelProposal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_proposalId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_voters",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_yes",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_no",
        type: "uint256",
      },
    ],
    name: "collectProposal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_createdBy",
        type: "address",
      },
      {
        internalType: "address",
        name: "_target",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
      {
        internalType: "string",
        name: "_ipfs",
        type: "string",
      },
    ],
    name: "createProposal",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "destroyed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_executeBy",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_proposalId",
        type: "uint256",
      },
    ],
    name: "executeProposal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_startIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_count",
        type: "uint256",
      },
    ],
    name: "listProposals",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "proposalId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "createdBy",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "yes",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "no",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "voters",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "ipfs",
            type: "string",
          },
          {
            internalType: "address",
            name: "target",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "value",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "snapshot",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "collected",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "executed",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "canceled",
            type: "bool",
          },
        ],
        internalType: "struct IEtherZDAO.Proposal[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "numberOfProposals",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "_destroyed",
        type: "bool",
      },
    ],
    name: "setDestroyed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_gnosisSafe",
        type: "address",
      },
    ],
    name: "setGnosisSafe",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "setVotingToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_proposalId",
        type: "uint256",
      },
    ],
    name: "state",
    outputs: [
      {
        internalType: "enum IEtherZDAO.ProposalState",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "zDAOOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IEtherZDAO__factory {
  static readonly abi = _abi;
  static createInterface(): IEtherZDAOInterface {
    return new utils.Interface(_abi) as IEtherZDAOInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEtherZDAO {
    return new Contract(address, _abi, signerOrProvider) as IEtherZDAO;
  }
}
