/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPolyZDAOChef, IPolyZDAOChefInterface } from "../IPolyZDAOChef";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "_zDAO",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "_isRelativeMajority",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_threshold",
        type: "uint256",
      },
    ],
    name: "DAOCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
    ],
    name: "DAODestroyed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_daoId",
        type: "uint256",
      },
    ],
    name: "getzDAOById",
    outputs: [
      {
        internalType: "contract IPolyZDAO",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_startIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_endIndex",
        type: "uint256",
      },
    ],
    name: "listzDAOs",
    outputs: [
      {
        internalType: "contract IPolyZDAO[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "numberOfzDAOs",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPolyZDAOChef__factory {
  static readonly abi = _abi;
  static createInterface(): IPolyZDAOChefInterface {
    return new utils.Interface(_abi) as IPolyZDAOChefInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPolyZDAOChef {
    return new Contract(address, _abi, signerOrProvider) as IPolyZDAOChef;
  }
}
