/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IRootTunnel, IRootTunnelInterface } from "../IRootTunnel";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "sendMessageToChild",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRootTunnel__factory {
  static readonly abi = _abi;
  static createInterface(): IRootTunnelInterface {
    return new utils.Interface(_abi) as IRootTunnelInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRootTunnel {
    return new Contract(address, _abi, signerOrProvider) as IRootTunnel;
  }
}
