/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRootStateReceiver,
  IRootStateReceiverInterface,
} from "../IRootStateReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "processMessageFromChild",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRootStateReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IRootStateReceiverInterface {
    return new utils.Interface(_abi) as IRootStateReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRootStateReceiver {
    return new Contract(address, _abi, signerOrProvider) as IRootStateReceiver;
  }
}
