/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRootStateSender,
  IRootStateSenderInterface,
} from "../IRootStateSender";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "sendMessageToChild",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRootStateSender__factory {
  static readonly abi = _abi;
  static createInterface(): IRootStateSenderInterface {
    return new utils.Interface(_abi) as IRootStateSenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRootStateSender {
    return new Contract(address, _abi, signerOrProvider) as IRootStateSender;
  }
}
