/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IzDAOCore, IzDAOCoreInterface } from "../IzDAOCore";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "string",
        name: "daoId",
        type: "string",
      },
      {
        indexed: true,
        internalType: "string",
        name: "metadataUri",
        type: "string",
      },
    ],
    name: "DAOCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "string",
        name: "daoId",
        type: "string",
      },
      {
        indexed: true,
        internalType: "string",
        name: "zNA",
        type: "string",
      },
    ],
    name: "DAOzNAAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "string",
        name: "daoId",
        type: "string",
      },
      {
        indexed: true,
        internalType: "string",
        name: "zNA",
        type: "string",
      },
    ],
    name: "DAOzNARemoved",
    type: "event",
  },
];

export class IzDAOCore__factory {
  static readonly abi = _abi;
  static createInterface(): IzDAOCoreInterface {
    return new utils.Interface(_abi) as IzDAOCoreInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IzDAOCore {
    return new Contract(address, _abi, signerOrProvider) as IzDAOCore;
  }
}
