/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IZDAOCore, IZDAOCoreInterface } from "../IZDAOCore";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "daoId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "ens",
        type: "uint256",
      },
    ],
    name: "DAOCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "daoId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "zNA",
        type: "uint256",
      },
    ],
    name: "LinkAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "daoId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "zNA",
        type: "uint256",
      },
    ],
    name: "LinkRemoved",
    type: "event",
  },
];

export class IZDAOCore__factory {
  static readonly abi = _abi;
  static createInterface(): IZDAOCoreInterface {
    return new utils.Interface(_abi) as IZDAOCoreInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IZDAOCore {
    return new Contract(address, _abi, signerOrProvider) as IZDAOCore;
  }
}
