/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IZDAORegistry, IZDAORegistryInterface } from "../IZDAORegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "daoId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "ensSpace",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "gnosisSafe",
        type: "address",
      },
    ],
    name: "DAOCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "daoId",
        type: "uint256",
      },
    ],
    name: "DAODestroyed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "daoId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "endSpace",
        type: "string",
      },
      {
        indexed: false,
        internalType: "address",
        name: "gnosisSafe",
        type: "address",
      },
    ],
    name: "DAOModified",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "daoId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "zNA",
        type: "uint256",
      },
    ],
    name: "LinkAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "daoId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "zNA",
        type: "uint256",
      },
    ],
    name: "LinkRemoved",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "zNA",
        type: "uint256",
      },
    ],
    name: "doeszDAOExistForzNA",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "ensSpace",
        type: "string",
      },
    ],
    name: "getzDAOByEns",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "ensSpace",
            type: "string",
          },
          {
            internalType: "address",
            name: "gnosisSafe",
            type: "address",
          },
          {
            internalType: "uint256[]",
            name: "associatedzNAs",
            type: "uint256[]",
          },
          {
            internalType: "bool",
            name: "destroyed",
            type: "bool",
          },
        ],
        internalType: "struct IZDAORegistry.ZDAORecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "daoId",
        type: "uint256",
      },
    ],
    name: "getzDAOById",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "ensSpace",
            type: "string",
          },
          {
            internalType: "address",
            name: "gnosisSafe",
            type: "address",
          },
          {
            internalType: "uint256[]",
            name: "associatedzNAs",
            type: "uint256[]",
          },
          {
            internalType: "bool",
            name: "destroyed",
            type: "bool",
          },
        ],
        internalType: "struct IZDAORegistry.ZDAORecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "zNA",
        type: "uint256",
      },
    ],
    name: "getzDaoByZNA",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "ensSpace",
            type: "string",
          },
          {
            internalType: "address",
            name: "gnosisSafe",
            type: "address",
          },
          {
            internalType: "uint256[]",
            name: "associatedzNAs",
            type: "uint256[]",
          },
          {
            internalType: "bool",
            name: "destroyed",
            type: "bool",
          },
        ],
        internalType: "struct IZDAORegistry.ZDAORecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "startIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "endIndex",
        type: "uint256",
      },
    ],
    name: "listzDAOs",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "ensSpace",
            type: "string",
          },
          {
            internalType: "address",
            name: "gnosisSafe",
            type: "address",
          },
          {
            internalType: "uint256[]",
            name: "associatedzNAs",
            type: "uint256[]",
          },
          {
            internalType: "bool",
            name: "destroyed",
            type: "bool",
          },
        ],
        internalType: "struct IZDAORegistry.ZDAORecord[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "numberOfzDAOs",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IZDAORegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IZDAORegistryInterface {
    return new utils.Interface(_abi) as IZDAORegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IZDAORegistry {
    return new Contract(address, _abi, signerOrProvider) as IZDAORegistry;
  }
}
