/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { ZNSHubTest, ZNSHubTestInterface } from "../ZNSHubTest";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "domainId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "domainId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "setOwnerOf",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610149806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806322e670b41461003b5780636352211e14610079575b600080fd5b6100776100493660046100be565b60009182526020829052604090912080546001600160a01b0319166001600160a01b03909216919091179055565b005b6100a26100873660046100fa565b6000908152602081905260409020546001600160a01b031690565b6040516001600160a01b03909116815260200160405180910390f35b600080604083850312156100d157600080fd5b8235915060208301356001600160a01b03811681146100ef57600080fd5b809150509250929050565b60006020828403121561010c57600080fd5b503591905056fea2646970667358221220251bbf5743801141f41846c726e9e8ff707c61244c10ab4908ad1cac98c1a43464736f6c63430008090033";

export class ZNSHubTest__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ZNSHubTest> {
    return super.deploy(overrides || {}) as Promise<ZNSHubTest>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ZNSHubTest {
    return super.attach(address) as ZNSHubTest;
  }
  connect(signer: Signer): ZNSHubTest__factory {
    return super.connect(signer) as ZNSHubTest__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ZNSHubTestInterface {
    return new utils.Interface(_abi) as ZNSHubTestInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ZNSHubTest {
    return new Contract(address, _abi, signerOrProvider) as ZNSHubTest;
  }
}
